import { defineConfig } from 'vitepress'

export default defineConfig({
	title: 'RxJS Operator Suffixes',
	description: 'RxJS operator naming conventions grouped by base name and suffix',
	ignoreDeadLinks: true,
	themeConfig: {
		nav: [
			{ text: 'Home', link: '/' },
			{ text: 'Suffix Reference', link: '/suffix-overview' },
			{ text: 'Decision Trees', link: '/decisions/' },
			{ text: 'Operator Deep Dives', link: '/operators/map' },
		],
		sidebar: [
			{
				text: 'Suffix Reference',
				items: [
					{ text: 'Overview', link: '/suffix-overview' },
					{
						text: 'Higher-Order / Flattening',
						link: '/categories/flattening',
					},
					{
						text: 'Windowing & Buffering',
						link: '/categories/windowing-buffering',
					},
					{ text: 'Rate Limiting', link: '/categories/rate-limiting' },
					{ text: 'Transformation', link: '/categories/transformation' },
					{ text: 'Filtering', link: '/categories/filtering' },
					{ text: 'Combination', link: '/categories/combination' },
					{ text: 'Creation', link: '/categories/creation' },
					{
						text: 'Multicasting & Sharing',
						link: '/categories/multicasting',
					},
					{
						text: 'Error Handling & Recovery',
						link: '/categories/error-handling',
					},
					{ text: 'Side Effects', link: '/categories/side-effects' },
					{
						text: 'Notification Objects',
						link: '/categories/notification',
					},
					{
						text: 'Scheduling & Timing',
						link: '/categories/scheduling-timing',
					},
				],
			},
			{
				text: 'Decision Trees',
				items: [
					{ text: 'Overview', link: '/decisions/' },
					{ text: 'Higher-Order / Flattening', link: '/decisions/flattening' },
					{ text: 'Windowing & Buffering', link: '/decisions/windowing-buffering' },
					{ text: 'Rate Limiting', link: '/decisions/rate-limiting' },
					{ text: 'Transformation', link: '/decisions/transformation' },
					{ text: 'Filtering', link: '/decisions/filtering' },
					{ text: 'Combination', link: '/decisions/combination' },
					{ text: 'Creation', link: '/decisions/creation' },
					{ text: 'Multicasting & Sharing', link: '/decisions/multicasting' },
					{ text: 'Error Handling & Recovery', link: '/decisions/error-handling' },
					{ text: 'Side Effects', link: '/decisions/side-effects' },
					{ text: 'Notification Objects', link: '/decisions/notification' },
					{ text: 'Scheduling & Timing', link: '/decisions/scheduling-timing' },
				],
			},
			{
				text: 'Operator Deep Dives',
				collapsed: true,
				items: [
					{
						text: 'Higher-Order / Flattening',
						collapsed: true,
						items: [
							{ text: 'concat', link: '/operators/concat' },
							{ text: 'concatAll', link: '/operators/concatAll' },
							{ text: 'concatMap', link: '/operators/concatMap' },
							{ text: 'concatMapTo', link: '/operators/concatMapTo' },
							{ text: 'concatWith', link: '/operators/concatWith' },
							{ text: 'exhaustAll', link: '/operators/exhaustAll' },
							{ text: 'exhaustMap', link: '/operators/exhaustMap' },
							{ text: 'merge', link: '/operators/merge' },
							{ text: 'mergeAll', link: '/operators/mergeAll' },
							{ text: 'mergeMap', link: '/operators/mergeMap' },
							{ text: 'mergeMapTo', link: '/operators/mergeMapTo' },
							{ text: 'mergeScan', link: '/operators/mergeScan' },
							{ text: 'mergeWith', link: '/operators/mergeWith' },
							{ text: 'switchAll', link: '/operators/switchAll' },
							{ text: 'switchMap', link: '/operators/switchMap' },
							{ text: 'switchMapTo', link: '/operators/switchMapTo' },
							{ text: 'switchScan', link: '/operators/switchScan' },
						],
					},
					{
						text: 'Windowing & Buffering',
						collapsed: true,
						items: [
							{ text: 'buffer', link: '/operators/buffer' },
							{ text: 'bufferCount', link: '/operators/bufferCount' },
							{ text: 'bufferTime', link: '/operators/bufferTime' },
							{ text: 'bufferToggle', link: '/operators/bufferToggle' },
							{ text: 'bufferWhen', link: '/operators/bufferWhen' },
							{ text: 'window', link: '/operators/window' },
							{ text: 'windowCount', link: '/operators/windowCount' },
							{ text: 'windowTime', link: '/operators/windowTime' },
							{ text: 'windowToggle', link: '/operators/windowToggle' },
							{ text: 'windowWhen', link: '/operators/windowWhen' },
						],
					},
					{
						text: 'Rate Limiting',
						collapsed: true,
						items: [
							{ text: 'audit', link: '/operators/audit' },
							{ text: 'auditTime', link: '/operators/auditTime' },
							{ text: 'debounce', link: '/operators/debounce' },
							{ text: 'debounceTime', link: '/operators/debounceTime' },
							{ text: 'sample', link: '/operators/sample' },
							{ text: 'sampleTime', link: '/operators/sampleTime' },
							{ text: 'throttle', link: '/operators/throttle' },
							{ text: 'throttleTime', link: '/operators/throttleTime' },
						],
					},
					{
						text: 'Transformation',
						collapsed: true,
						items: [
							{ text: 'map', link: '/operators/map' },
							{ text: 'mapTo', link: '/operators/mapTo' },
							{ text: 'scan', link: '/operators/scan' },
							{ text: 'expand', link: '/operators/expand' },
							{ text: 'pairwise', link: '/operators/pairwise' },
							{ text: 'groupBy', link: '/operators/groupBy' },
						],
					},
					{
						text: 'Filtering',
						collapsed: true,
						items: [
							{ text: 'distinct', link: '/operators/distinct' },
							{ text: 'distinctUntilChanged', link: '/operators/distinctUntilChanged' },
							{ text: 'distinctUntilKeyChanged', link: '/operators/distinctUntilKeyChanged' },
							{ text: 'find', link: '/operators/find' },
							{ text: 'findIndex', link: '/operators/findIndex' },
							{ text: 'skip', link: '/operators/skip' },
							{ text: 'skipLast', link: '/operators/skipLast' },
							{ text: 'skipUntil', link: '/operators/skipUntil' },
							{ text: 'skipWhile', link: '/operators/skipWhile' },
							{ text: 'take', link: '/operators/take' },
							{ text: 'takeLast', link: '/operators/takeLast' },
							{ text: 'takeUntil', link: '/operators/takeUntil' },
							{ text: 'takeWhile', link: '/operators/takeWhile' },
							{ text: 'first', link: '/operators/first' },
							{ text: 'firstValueFrom', link: '/operators/firstValueFrom' },
							{ text: 'last', link: '/operators/last' },
							{ text: 'lastValueFrom', link: '/operators/lastValueFrom' },
							{ text: 'single', link: '/operators/single' },
							{ text: 'elementAt', link: '/operators/elementAt' },
							{ text: 'defaultIfEmpty', link: '/operators/defaultIfEmpty' },
							{ text: 'throwIfEmpty', link: '/operators/throwIfEmpty' },
						],
					},
					{
						text: 'Combination',
						collapsed: true,
						items: [
							{ text: 'combineLatest', link: '/operators/combineLatest' },
							{ text: 'combineLatestAll', link: '/operators/combineLatestAll' },
							{ text: 'combineLatestWith', link: '/operators/combineLatestWith' },
							{ text: 'zip', link: '/operators/zip' },
							{ text: 'zipAll', link: '/operators/zipAll' },
							{ text: 'zipWith', link: '/operators/zipWith' },
							{ text: 'race', link: '/operators/race' },
							{ text: 'raceWith', link: '/operators/raceWith' },
							{ text: 'forkJoin', link: '/operators/forkJoin' },
							{ text: 'withLatestFrom', link: '/operators/withLatestFrom' },
							{ text: 'startWith', link: '/operators/startWith' },
							{ text: 'endWith', link: '/operators/endWith' },
						],
					},
					{
						text: 'Creation',
						collapsed: true,
						items: [
							{ text: 'from', link: '/operators/from' },
							{ text: 'fromEvent', link: '/operators/fromEvent' },
							{ text: 'fromEventPattern', link: '/operators/fromEventPattern' },
							{ text: 'fromFetch', link: '/operators/fromFetch' },
							{ text: 'of', link: '/operators/of' },
							{ text: 'range', link: '/operators/range' },
							{ text: 'interval', link: '/operators/interval' },
							{ text: 'defer', link: '/operators/defer' },
							{ text: 'generate', link: '/operators/generate' },
						],
					},
					{
						text: 'Multicasting & Sharing',
						collapsed: true,
						items: [
							{ text: 'publish', link: '/operators/publish' },
							{ text: 'publishBehavior', link: '/operators/publishBehavior' },
							{ text: 'publishLast', link: '/operators/publishLast' },
							{ text: 'publishReplay', link: '/operators/publishReplay' },
							{ text: 'share', link: '/operators/share' },
							{ text: 'shareReplay', link: '/operators/shareReplay' },
						],
					},
					{
						text: 'Error Handling & Recovery',
						collapsed: true,
						items: [
							{ text: 'retry', link: '/operators/retry' },
							{ text: 'retryWhen', link: '/operators/retryWhen' },
							{ text: 'catchError', link: '/operators/catchError' },
							{ text: 'repeat', link: '/operators/repeat' },
							{ text: 'repeatWhen', link: '/operators/repeatWhen' },
						],
					},
					{
						text: 'Scheduling & Timing',
						collapsed: true,
						items: [
							{ text: 'delay', link: '/operators/delay' },
							{ text: 'delayWhen', link: '/operators/delayWhen' },
							{ text: 'observeOn', link: '/operators/observeOn' },
							{ text: 'subscribeOn', link: '/operators/subscribeOn' },
							{ text: 'timeInterval', link: '/operators/timeInterval' },
							{ text: 'timeout', link: '/operators/timeout' },
							{ text: 'timer', link: '/operators/timer' },
							{ text: 'timestamp', link: '/operators/timestamp' },
						],
					},
					{
						text: 'Side Effects & Notification',
						collapsed: true,
						items: [
							{ text: 'tap', link: '/operators/tap' },
							{ text: 'finalize', link: '/operators/finalize' },
							{ text: 'materialize', link: '/operators/materialize' },
							{ text: 'dematerialize', link: '/operators/dematerialize' },
						],
					},
				],
			},
			{
				text: 'Raw Data',
				collapsed: true,
				items: [
					{ text: 'Full API List', link: '/rxjs-api-function-list' },
				],
			},
		],
		outline: {
			level: [2, 3],
			label: 'On this page',
		},
		search: {
			provider: 'local',
		},
	},
})
