// scripts/extract-explanations.ts
// Run with: npx tsx scripts/extract-explanations.ts
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, basename } from 'node:path'

const CACHE_DIR = 'C:/Users/HP/Web/Frontend/rxjs/rxjs-operator-explain-claude'
const OUT_FILE  = 'src/data/explanations.ts'

interface OperatorExplanation {
	code:    string
	gotchas: string[]
	related: string
	rule:    string
}

function extractSection(content: string, heading: string): string {
	const headingPattern = new RegExp(`####\\s+${heading}\\s*\\n([\\s\\S]*?)(?=\\n####|\\n###|$)`)
	return (content.match(headingPattern)?.[1] ?? '').trim()
}

function extractCode(content: string): string {
	const section = extractSection(content, 'Code Example')
	const match = section.match(/```typescript\n([\s\S]*?)```/)
	return (match?.[1] ?? '').trim()
}

function extractGotchas(content: string): string[] {
	const section = extractSection(content, 'Gotchas')
	return section
		.split('\n')
		.filter(line => /^\d+\./.test(line.trim()))
		.map(line => line.replace(/^\d+\.\s*/, '').trim())
}

function extractRelated(content: string): string {
	return extractSection(content, 'Related Operators').trim()
}

function extractRule(content: string): string {
	const section = extractSection(content, 'Decision Rule')
	return section.replace(/^>\s*/gm, '').trim()
}

function stripFrontmatter(content: string): string {
	return content.replace(/^---[\s\S]*?---\n/, '')
}

const files = readdirSync(CACHE_DIR).filter(f => f.endsWith('.md') && f !== 'index.md')

const entries: Record<string, OperatorExplanation> = {}

for (const file of files) {
	const operatorName = basename(file, '.md')
	const raw = readFileSync(join(CACHE_DIR, file), 'utf-8')
	const content = stripFrontmatter(raw)

	entries[operatorName] = {
		code:    extractCode(content),
		gotchas: extractGotchas(content),
		related: extractRelated(content),
		rule:    extractRule(content),
	}
}

const output = `// src/data/explanations.ts
// Generated by scripts/extract-explanations.ts — do not edit manually.
// Re-generate with: npx tsx scripts/extract-explanations.ts

export interface OperatorExplanation {
\tcode:    string
\tgotchas: string[]
\trelated: string
\trule:    string
}

export const explanations: Record<string, OperatorExplanation> = ${JSON.stringify(entries, null, '\t')}
`

writeFileSync(OUT_FILE, output, 'utf-8')
console.log(`✓ Wrote ${Object.keys(entries).length} operators to ${OUT_FILE}`)
